global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: server
    static_configs:
      - targets:
          - 'host.docker.internal:4000'
