[build]
builder = "nixpacks"
buildCommand = "pnpm run --filter=@fstmswa/types graphql-codegen && pnpm run --filter=@fstmswa/app build"

[deploy]
startCommand = "pnpm run --filter=@fstmswa/app start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
