[build]
builder = "nixpacks"
buildCommand = "pnpm run graphql-codegen && pnpm nx run @fstmswa/app:build"

[deploy]
startCommand = "pnpm run start --prefix app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
