[build]
builder = "nixpacks"
buildCommand = "pnpm run --filter=@fstmswa/server build"

[deploy]
startCommand = "pnpm run --filter=@fstmswa/server start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
