[build]
builder = "nixpacks"
buildCommand = "pnpm run nx run @fstmswa/server:build"

[deploy]
startCommand = "pnpm run start --prefix server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
