name: ci

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: List mismatching dependencies
        run: pnpm run list-mismatches

      - name: Build GraphQL types
        run: pnpm run --filter=@fstmswa/type graphql-codegen

      - name: Build DB types
        run: pnpm run --filter=@fstmswa/server prisma generate

      - name: Test
        run: pnpm run test

      - name: Deploy Server
        if: github.ref == 'refs/heads/main'
        run: pnpm run railway up --service server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy App
        if: github.ref == 'refs/heads/main'
        run: pnpm run railway up --service app
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
