name: Deploy Web Application

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: List mismatching dependencies
        run: pnpm run list-mismatches

      - name: Build GraphQL types
        run: pnpm run graphql-codegen

      - name: Build DB types
        run: pnpm run prisma generate --prefix server

  test-app:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: pnpm run nx run @fstmswa/app:test

  test-server:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: pnpm run nx run @fstmswa/server:test

  deploy:
    runs-on: ubuntu-latest
    needs: [test-app, test-server]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy Server
        run: pnpm run railway up -- --service server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy App
        run: pnpm run railway up -- --service app
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
