name: Deploy Web Application

on: push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: List mismatching dependencies
        run: pnpm run list-mismatches

      - name: Build GraphQL types
        run: pnpm run graphql-codegen

      - name: Build DB types
        run: pnpm run prisma generate --prefix server

      - name: Test app
        run: pnpm run nx run @full-stack-typescript-monorepo-starter-with-authentication/app:test

      - name: Test server
        run: pnpm run nx run @full-stack-typescript-monorepo-starter-with-authentication/server:test

      - name: Deploy Server
        if: github.ref == 'refs/heads/master'
        run: pnpm run railway up -- --service server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy App
        if: github.ref == 'refs/heads/master'
        run: pnpm run railway up -- --service app
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
